### PR TITLE
Adaptive logging for all platforms

### LINKED ISSUE #567: Logging fail on android

### PR DESCRIPTION
**Pull request by JoGir**
resolves #567

### CODE REVIEW

**Comment by julianseeger** [comment]
+1 for this. But I would prefer `Qabel` over `Qbl`. So either `QabelLogger` or just the `Logger` in the `de.qabel.*` package.

**Comment by audax** [comment]
+1 for QabelLogger and not just Logger.

**Comment by julianseeger** [comment]
> This branch has conflicts that must be resolved

**Comment by julianseeger** [comment]
Out of interest: do we have any tests for this (or the old version)? Can't find any...

File: core/src/main/java/de/qabel/core/logging/DefaultQabelLogger.kt [hunk 1]
```diff
@@ -0,0 +1,28 @@
+package de.qabel.core.logging
+
+import org.slf4j.Logger
+import org.slf4j.LoggerFactory
+
+
+class DefaultQabelLogger(clazz: Class<*>) : QabelLoggerWrapper {
+
+    val logger: Logger = LoggerFactory.getLogger(clazz)
```
Comment (julianseeger) [inline core/src/main/java/de/qabel/core/logging/DefaultQabelLogger.kt]: by lazy. we don't need to initialize a logger until someone actually logs. especially on android where those classes might get garbage collected before they are not needed ^^

File: core/src/main/java/de/qabel/core/logging/QabelLogger.kt [hunk 2]
```diff
@@ -0,0 +1,21 @@
+package de.qabel.core.logging
+
+interface QabelLogger {
+    val logger: QabelLoggerWrapper
+        get() = QabelLoggerManager.factory.createLogger(javaClass)
```
Comment (julianseeger) [inline core/src/main/java/de/qabel/core/logging/QabelLogger.kt]: Pretty sure you are creating a new DefaultQabelLogger instance for each log message. If you make this val logger lazy instead of defining a getter, we should get one instance per QabelLogger implementation, which should be fine.

File: core/src/main/java/de/qabel/core/logging/QabelLogger.kt [hunk 3]
```diff
@@ -0,0 +1,21 @@
...
+}
+
+fun QabelLogger.trace(message: Any, vararg args: Any) =
```
Comment (julianseeger) [inline core/src/main/java/de/qabel/core/logging/QabelLogger.kt]: why are these extension methods? I would prefer them inside the interface body or doesn't Kotlin allow default implementations?

File: core/src/main/java/de/qabel/core/logging/QabelLoggerWrapper.kt [hunk 4]
```diff
@@ -0,0 +1,12 @@
+package de.qabel.core.logging
+
+interface QabelLoggerWrapper {
```
Comment (julianseeger) [inline core/src/main/java/de/qabel/core/logging/QabelLoggerWrapper.kt]: The naming goes the wrong way here. The QabelLogger looks like an implementation of the QabelLoggerWrapper

File: core/src/main/java/de/qabel/core/logging/QabelLogger.kt (hunk 3 above)
Comment (JoGir) [inline core/src/main/java/de/qabel/core/logging/QabelLogger.kt]: the using class only imports required logging methods...

File: core/src/main/java/de/qabel/core/logging/QabelLogger.kt (hunk 2 above)
Comment (JoGir) [inline core/src/main/java/de/qabel/core/logging/QabelLogger.kt]: Delegated properties not allowed in interfaces. looking for solutions...
